volumes:
  mongodb_data:

networks:
  wedding_website:

services:
  mongodb:
    image: mongo:8.0.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - wedding_website

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    networks:
      - wedding_website

  backend:
    image: ghcr.io/bioresestance/bromma_wood_wedding_server:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - wedding_website

  frontend:
    image: ghcr.io/bioresestance/bromma_wood_wedding_client:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - wedding_website

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    ports:
      - 4321:80
    networks:
      - wedding_website
    depends_on:
      - backend
      - frontend
