FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Set the working directory
WORKDIR /app

# Copy the rest of the application code
COPY ./Server .

# Install the application dependencies and use the existing lock file
RUN uv sync --frozen --no-install-project --no-dev 

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]