name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository_owner }}/BrommaWoodWedding

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          TAG=${GITHUB_REF##*/}
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            TAG="latest"
          fi

          for DOCKERFILE in $(ls production/*.Dockerfile); do
            IMAGE_NAME=$(basename ${DOCKERFILE} .Dockerfile)
            docker build -f ${DOCKERFILE} -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${IMAGE_NAME}-${TAG} .
            docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${IMAGE_NAME}-${TAG}
          done
